<?php
if (defined('DEBUG')) {    
}
else {
    define('DEBUG', true);
}

//////////////////////////////////////////////////////////////////////
//
// Form alter to customize the user interface of content managemeng
//
//////////////////////////////////////////////////////////////////////
function texvox_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == "branch_node_form"){
    $form['actions']['submit']['#submit'][] = 'texvox_branch_form_submit_nested_handler';
  }
  if($form_id == "screen_node_form"){
    $form['actions']['submit']['#submit'][] = 'texvox_screen_form_submit_nested_handler';
  }
  if($form_id == "screen_menu_node_form"){
    $form['actions']['submit']['#submit'][] = 'texvox_screen_menu_form_submit_nested_handler';
  }
  //filter for menu goto screens in IVR form
  if($form_id == "ivr_node_form"){
    $current_screens = $form['field_ivr_screen']['und']['entities'];
    $current_screen_menu_options = array();
    $current_screen_menu_options['_none'] = "- None -";
    //get screen ids in this IVR
    foreach ($current_screens as $key => $screen) {
      if(is_numeric($key) and isset($screen['#entity']) and !empty($screen['#entity'])){
        $index = intval($screen['#entity']->nid);
        $current_screen_menu_options[$index] = $screen['#entity']->title;
      }
    }
    // dpm($current_screen_menu_options);
    // dpm($form);
    $form['actions']['submit']['#submit'][] = 'texvox_ivr_form_submit_nested_handler';
    $screens_count = count($current_screen_menu_options) - 1;
    if($screens_count > 0){
      //already has screens in this IVR
      $screens = $form['field_ivr_screen']['und']['entities'];
      foreach ($screens as $skey => $screen) {
        if(is_numeric($skey) and isset($screen['form']) and !empty($screen['form'])){
          $menus = $screen['form']['field_menus'];
          // For menus as nodes
          if(isset($menus) and isset($menus['und'])){
            $menu_form = $menus['und']['form'];
            if(isset($menu_form)){
              // create a new menu
              $options = $menu_form['field_go_to_screen']['und']['#options'];
              $form['field_ivr_screen']['und']['entities'][$skey]['form']['field_menus']['und']['form']['field_go_to_screen']['und']['#options'] = $current_screen_menu_options;
            }
            else{
              // edit an exist menu
              foreach ($menus['und']['entities'] as $mkey => $deep_menu) {            
                if(is_numeric($mkey) and isset($deep_menu['form']) and !empty($deep_menu['form'])){
                  // dpm($mkey);
                  $form['field_ivr_screen']['und']['entities'][$skey]['form']['field_menus']['und']['entities'][$mkey]['form']['field_go_to_screen']['und']['#options'] = $current_screen_menu_options;
                }
              }
            }
          }

          // For menus as field collections
          // foreach ($menus as $mkey => $menu) {
          //   if(is_numeric($mkey) and isset($menu['field_go_to_screen']) and !empty($menu['field_go_to_screen'])){
          //     $options = $menu['field_go_to_screen']['und']['#options'];
          //     $form['field_ivr_screen']['und']['entities'][$skey]['form']['field_menus']['und'][$mkey]['field_go_to_screen']['und']['#options'] = $current_screen_menu_options;
          //   }
          // }
        }
      }
    }
    else{
      //No screens in this IVR
      $form['field_ivr_screen']['und']['form']['field_menus']['und']['form']['field_go_to_screen']['und']['#options'] = $current_screen_menu_options;
    }
  }

  // //filter for menu goto screens in screen form
  // if($form_id == "screen_node_form"){
  //   dpm($form);
  //   if(isset($form['#node']->nid)){
  //     // edit form
  //     $nid = intval($form['#node']->nid);
  //     $query="SELECT entity_id FROM field_data_field_ivr_screen WHERE entity_type ='node' AND bundle='ivr' AND field_ivr_screen_target_id=$nid LIMIT 1";
  //     $result=db_query($query);
  //     foreach ($result as $row) {
  //       $IVR_ID = intval($row->entity_id);
  //     }
  //     $menu = $form['field_menus']['und'];
  //     if(isset($IVR_ID)){
  //       $query="SELECT field_ivr_screen_target_id FROM field_data_field_ivr_screen WHERE entity_type ='node' AND bundle='ivr' AND entity_id=$IVR_ID";
  //       $result=db_query($query);
  //       $screen_ids = array();
  //       foreach ($result as $row) {
  //         $screen_ids[] = intval($row->field_ivr_screen_target_id);
  //       }
  //       // dpm($screen_ids);
        
  //       if(isset($menu['form'])){
  //         $options = $form['field_menus']['und']['form']['field_go_to_screen']['und']['#options'];
  //         foreach ($options as $key => $op) {
  //           if(intval($key) > 0 and !in_array(intval($key), $screen_ids)){
  //             unset($form['field_menus']['und']['form']['field_go_to_screen']['und']['#options'][$key]);
  //           }
  //         }
  //       }
  //     }
  //     else{
  //       if(isset($menu['form'])){
  //         $current_screen_menu_options = array();
  //         $current_screen_menu_options['_none'] = "- None -";
  //         $form['field_menus']['und']['form']['field_go_to_screen']['und']['#options'] = $current_screen_menu_options;
  //       }
  //     }
  //   }
  //   else{
  //     // new form
  //     $menu = $form['field_menus']['und'];
  //     if(isset($menu['form'])){
  //       // $options = $form['field_menus']['und']['form']['field_go_to_screen']['und']['#options'];
  //       // foreach ($options as $key => $op) {
  //       //   if(intval($key) > 0){
  //       //     unset($form['field_menus']['und']['form']['field_go_to_screen']['und']['#options'][$key]);
  //       //   }
  //       // }

  //       $current_screen_menu_options = array();
  //       $current_screen_menu_options['_none'] = "- None -";
  //       $form['field_menus']['und']['form']['field_go_to_screen']['und']['#options'] = $current_screen_menu_options;
  //     }
  //   }
  // }
}



/**
 * change updated timestamp for referenced organization
 */
function texvox_branch_form_submit_nested_handler($form, &$form_state){
  $timestamp = time();
  $org_id = intval($form['field_organization']['und']['#value']);
  $result = db_update('node') // Table name no longer needs {}
              ->fields(array(
                'changed' => $timestamp,
              ))
              ->condition('nid', $org_id, '=')
              ->execute();
  // update all the other branches of this org
  $sql = "UPDATE node as n 
          left join field_data_field_organization as o on o.entity_id = n.nid
          set n.changed = :updated
          where o.field_organization_target_id = :org_id";

  $args = array(':updated' => $timestamp, ':org_id' => $org_id);
  $result = db_query($sql, $args);
}


/**
 * change updated timestamp for referenced screens and menus
 */
function texvox_ivr_form_submit_nested_handler($form, &$form_state){
  $timestamp = time();
  $nid = intval($form_state['values']['nid']);  
  // screen level
  $sql_2 = "UPDATE field_data_field_ivr_screen as ss 
          left join node as update_screen on update_screen.nid = ss.field_ivr_screen_target_id
          set update_screen.changed = :updated
          where ss.entity_id = :nid";

  $args_2 = array(':updated' => $timestamp, ':nid' => $nid);
  $result = db_query($sql_2, $args_2);

  // menu level
  $sql_3 = "UPDATE field_data_field_ivr_screen as ss 
          left join field_data_field_menus as m on m.entity_id = ss.field_ivr_screen_target_id
          left join node as menu on menu.nid = m.field_menus_target_id
          set menu.changed = :updated
          where ss.entity_id = :nid";

  $args_3 = array(':updated' => $timestamp, ':nid' => $nid);
  $result = db_query($sql_3, $args_3);
}


/**
 * change updated timestamp for referenced ivr
 */
function texvox_screen_form_submit_nested_handler($form, &$form_state){
  $timestamp = time();
  $nid = intval($form_state['values']['nid']);
  $sql = "UPDATE node as n 
          left join field_data_field_ivr_screen as s on s.entity_id = n.nid
          set n.changed = :updated
          where s.field_ivr_screen_target_id = :nid";

  $args = array(':updated' => $timestamp, ':nid' => $nid);
  $result = db_query($sql, $args);

  // screen level
  $sql_2 = "UPDATE field_data_field_ivr_screen as s 
          left join node as ivr on s.entity_id = ivr.nid 
          left join field_data_field_ivr_screen as ss on ss.entity_id = ivr.nid
          left join node as update_screen on update_screen.nid = ss.field_ivr_screen_target_id
          set update_screen.changed = :updated
          where s.field_ivr_screen_target_id = :nid";

  $args_2 = array(':updated' => $timestamp, ':nid' => $nid);
  $result = db_query($sql_2, $args_2);

  // menu level
  $sql_3 = "UPDATE field_data_field_ivr_screen as s 
          left join node as ivr on s.entity_id = ivr.nid 
          left join field_data_field_ivr_screen as ss on ss.entity_id = ivr.nid
          left join field_data_field_menus as m on m.entity_id = ss.field_ivr_screen_target_id
          left join node as menu on menu.nid = m.field_menus_target_id
          set menu.changed = :updated
          where s.field_ivr_screen_target_id = :nid";

  $args_3 = array(':updated' => $timestamp, ':nid' => $nid);
  $result = db_query($sql_3, $args_3);
}


/**
 * change updated timestamp for referenced branch
 */
function texvox_screen_menu_form_submit_nested_handler($form, &$form_state){
  $timestamp = time();
  $nid = intval($form_state['values']['nid']);  
  // Find IVR
  $query = db_select('field_data_field_ivr_screen', 's');
  $query->join('field_data_field_menus', 'm', 'm.entity_id = s.field_ivr_screen_target_id');
  $result = $query->fields('s', array('entity_id'))
             ->condition('m.field_menus_target_id', $nid, '=')
             ->execute();
  $ivrID = 0;
  foreach ($result as $row) {
    $ivrID = intval($row->entity_id);
  }
  if($ivrID > 0){
    // ivr level
    $result = db_update('node')
                ->fields(array(
                    'changed' => $timestamp,
                  ))
                ->condition('nid', $ivrID, '=')
                ->execute();
    // screen level
    $sql_2 = "UPDATE field_data_field_ivr_screen as ss 
            left join node as update_screen on update_screen.nid = ss.field_ivr_screen_target_id
            set update_screen.changed = :updated
            where ss.entity_id = :nid";

    $args_2 = array(':updated' => $timestamp, ':nid' => $ivrID);
    $result = db_query($sql_2, $args_2);

    // menu level
    $sql_3 = "UPDATE field_data_field_ivr_screen as ss 
            left join field_data_field_menus as m on m.entity_id = ss.field_ivr_screen_target_id
            left join node as menu on menu.nid = m.field_menus_target_id
            set menu.changed = :updated
            where ss.entity_id = :nid";

    $args_3 = array(':updated' => $timestamp, ':nid' => $ivrID);
    $result = db_query($sql_3, $args_3);
  }
}



/**
 * Implements hook_views_api().
 */
function texvox_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'texvox'),
  );
}

/**
 * Implementation of hook_views_query_alter
 * @param $view
 * @param $query
 */
function texvox_views_query_alter(&$view, &$query) {
  if ($view->name == 'new_content') {
    $url = request_uri();
    $temp = explode('/', $url);
    $timestamp = intval($temp[(count($temp)-1)]);
    $view->query->where[1]['conditions'][0]['field']="node.changed";
    $view->query->where[1]['conditions'][0]['value']=$timestamp;
    $view->query->where[1]['conditions'][0]['operator']=">=";    
  }
}

/**
 * Implementation of hook_rules_action_info
 * Use rule to delete related nodes
 */

function texvox_rules_action_info(){
  $items['texvox_delete_ivr_when_delete_branch'] = array(
    'label' => t('Delete all IVRs related to this branch'), 
    'parameter' => array(
      'node' => array(
        'type' => 'node',
        'label' => t('Node'),
      ),        
    ), 
    'group' => t('Texvox Delete Nodes Rules'),
    'callbacks' => array(
      'execute' => 'texvox_delete_ivr_when_delete_branch',
    ),
    'base' => 'texvox_delete_ivr_when_delete_branch',
  );
  $items['texvox_delete_branch_when_delete_organization'] = array(
    'label' => t('Delete all branches related to this organization'), 
    'parameter' => array(
      'node' => array(
        'type' => 'node',
        'label' => t('Node'),
      ),        
    ), 
    'group' => t('Texvox Delete Nodes Rules'),
    'callbacks' => array(
      'execute' => 'texvox_delete_branch_when_delete_organization',
    ),
    'base' => 'texvox_delete_branch_when_delete_organization',
  );
  return $items;
}

/*
 * DELETE ivrs when delete a branch
 */
function texvox_delete_ivr_when_delete_branch($node){

  // watchdog('Node Delete', '<pre>'. print_r($node, TRUE) .'</pre>');
  $nid = intval($node->nid);
  $and = db_and()->condition('entity_type', 'node')->condition('bundle', 'ivr')->condition('field_branch_target_id', $nid);
  
  $result = db_select('field_data_field_branch', 'n')
      ->fields('n', array('entity_id'))
      ->condition($and)
      ->execute();
  
  $node_id_array = array();
  foreach ($result as $row) {
    $ivrID = intval($row->entity_id);
    $node_id_array[] = $ivrID;
  }
  node_delete_multiple($node_id_array);
}

/*
 * DELETE branches when delete an organization
 */
function texvox_delete_branch_when_delete_organization($node){

  // watchdog('Node Delete', '<pre>'. print_r($node, TRUE) .'</pre>');
  $nid = intval($node->nid);
  $and = db_and()->condition('entity_type', 'node')->condition('bundle', 'branch')->condition('field_organization_target_id', $nid);
  
  $result = db_select('field_data_field_organization', 'n')
      ->fields('n', array('entity_id'))
      ->condition($and)
      ->execute();
  
  $node_id_array = array();
  foreach ($result as $row) {
    $ivrID = intval($row->entity_id);
    $node_id_array[] = $ivrID;
  }
  node_delete_multiple($node_id_array);
}


/*
 * Register API:
 * [POST] http://live-texvox.pantheon.io/api/user/register
 * {
 * "name":"username",
 * "mail":"emailAddress",
 * "pass":"plainText"
 * }
 * NOTE: Need to login once it response without error message, Drupal has some issues for auto 
 * login after REST register
 *
 * Login API:
 * [POST] http://live-texvox.pantheon.io/api/user/login
 * {
 * "username":"username",
 * "password":"plainText" 
 * }
 * NOTE: App should keep the "token" and "user['uid']", and might need these to logout and reset 
 * password
 *
 * Forget password API:
 * [POST] http://live-texvox.pantheon.io/api/user/request_new_password
 * {
 * "name":"username"
 * }
 *
 * Reset Password API:
 * [PUT] http://live-texvox.pantheon.io/auth-api/user/:id
 * - Headers:
 *    X-CSRF-Token:TokenReceived 
 * 
 * - Payload:
 *    {
 *    "pass":"newPassword",
 *    "current_pass":"oldPassword"
 *    }
 *
 * Logout API:
 * [POST] http://live-texvox.pantheon.io/auth-api/user/logout
 * - Headers:
 *    X-CSRF-Token:TokenReceived 
 *
 */




